services:
  - docker

before_install:
  - docker pull opensutd/web-platform:latest-dev

script:
  - docker run --rm --env GH_ACCESS_TOKEN=${GH_ACCESS_TOKEN} -v ${PWD}:/app opensutd/web-platform:latest-dev bash -c './refresh_db.sh && python3 manage.py test'
  - docker run --rm --env GH_ACCESS_TOKEN=${GH_ACCESS_TOKEN} -v ${PWD}:/app opensutd/web-platform:latest-dev bash -c './refresh_db.sh && coverage run --source=. manage.py test'
  - docker run --rm --env GH_ACCESS_TOKEN=${GH_ACCESS_TOKEN} -v ${PWD}:/app opensutd/web-platform:latest-dev bash -c 'coveralls'
